# TCL File Generated by Component Editor 18.1
# Thu Jun 26 16:53:20 PDT 2025
# DO NOT MODIFY


# 
# GPIO_Driver "GPIO_Driver" v1.0
#  2025.06.26.16:53:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GPIO_Driver
# 
set_module_property DESCRIPTION ""
set_module_property NAME GPIO_Driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME GPIO_Driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gpio_driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gpio_driver.sv SYSTEM_VERILOG PATH ../../snake_game/verilog/gpio_driver.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point hps
# 
add_interface hps avalon end
set_interface_property hps addressUnits WORDS
set_interface_property hps associatedClock clock
set_interface_property hps associatedReset reset
set_interface_property hps bitsPerSymbol 8
set_interface_property hps burstOnBurstBoundariesOnly false
set_interface_property hps burstcountUnits WORDS
set_interface_property hps explicitAddressSpan 0
set_interface_property hps holdTime 0
set_interface_property hps linewrapBursts false
set_interface_property hps maximumPendingReadTransactions 0
set_interface_property hps maximumPendingWriteTransactions 0
set_interface_property hps readLatency 0
set_interface_property hps readWaitTime 1
set_interface_property hps setupTime 0
set_interface_property hps timingUnits Cycles
set_interface_property hps writeWaitTime 0
set_interface_property hps ENABLED true
set_interface_property hps EXPORT_OF ""
set_interface_property hps PORT_NAME_MAP ""
set_interface_property hps CMSIS_SVD_VARIABLES ""
set_interface_property hps SVD_ADDRESS_GROUP ""

add_interface_port hps hps_address address Input 4
add_interface_port hps hps_read read Input 1
add_interface_port hps hps_waitrequest waitrequest Output 1
add_interface_port hps hps_readdata readdata Output 32
add_interface_port hps hps_write write Input 1
add_interface_port hps hps_writedata writedata Input 32
set_interface_assignment hps embeddedsw.configuration.isFlash 0
set_interface_assignment hps embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps embeddedsw.configuration.isPrintableDevice 0


# 
# connection point gpio_0
# 
add_interface gpio_0 conduit end
set_interface_property gpio_0 associatedClock clock
set_interface_property gpio_0 associatedReset ""
set_interface_property gpio_0 ENABLED true
set_interface_property gpio_0 EXPORT_OF ""
set_interface_property gpio_0 PORT_NAME_MAP ""
set_interface_property gpio_0 CMSIS_SVD_VARIABLES ""
set_interface_property gpio_0 SVD_ADDRESS_GROUP ""

add_interface_port gpio_0 gpio_0 export Bidir 36


# 
# connection point gpio_1
# 
add_interface gpio_1 conduit end
set_interface_property gpio_1 associatedClock clock
set_interface_property gpio_1 associatedReset ""
set_interface_property gpio_1 ENABLED true
set_interface_property gpio_1 EXPORT_OF ""
set_interface_property gpio_1 PORT_NAME_MAP ""
set_interface_property gpio_1 CMSIS_SVD_VARIABLES ""
set_interface_property gpio_1 SVD_ADDRESS_GROUP ""

add_interface_port gpio_1 gpio_1 export Bidir 36


# 
# connection point debug_reset
# 
add_interface debug_reset conduit end
set_interface_property debug_reset associatedClock clock
set_interface_property debug_reset associatedReset ""
set_interface_property debug_reset ENABLED true
set_interface_property debug_reset EXPORT_OF ""
set_interface_property debug_reset PORT_NAME_MAP ""
set_interface_property debug_reset CMSIS_SVD_VARIABLES ""
set_interface_property debug_reset SVD_ADDRESS_GROUP ""

add_interface_port debug_reset dbg_rst_n export Input 1

